export const ADD_BOOKING_INIT = "ADD_BOOKING_INIT";
export const ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS";
export const ADD_BOOKING_FAIL = "ADD_BOOKING_FAIL";

export const GET_TYPE_BY_WHEELS_INIT = "GET_TYPE_BY_WHEELS_INIT";
export const GET_TYPE_BY_WHEELS_SUCCESS = "GET_TYPE_BY_WHEELS_SUCCESS";
export const GET_TYPE_BY_WHEELS_FAIL = "GET_TYPE_BY_WHEELS_FAIL";

export const GET_MODEL_BY_TYPE_INIT = "GET_MODEL_BY_TYPE_INIT";
export const GET_MODEL_BY_TYPE_SUCCESS = "GET_MODEL_BY_TYPE_SUCCESS";
export const GET_MODEL_BY_TYPE_FAIL = "GET_MODEL_BY_TYPE_FAIL";

export const GET_BOOKINGS_INIT = "GET_BOOKINGS_INIT";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
export const GET_BOOKINGS_FAIL = "GET_BOOKINGS_FAIL";
